In [2]:
import numpy as np
import cv2
#ee

In [2]:
# Particular image in this case would contain (512*512) rows and columns meaning 262,144 pixels
ROWS =  512
COLS =  512

In [4]:
# Opening the input image (RAW)
fin = open('C:/Users/avish/Desktop/New folder/barbara_gray.raw')     
print(fin)

<_io.TextIOWrapper name='C:/Users/avish/Desktop/New folder/barbara_gray.raw' mode='r' encoding='cp1252'>


In [5]:
print("... Load input image")
img = np.fromfile(fin, dtype = np.uint8, count = ROWS * COLS)  #Construct an array from data in a text or binary file
print("Dimension of the old image array: ", img.ndim)
print("Size of the old image array: ", img.size)

... Load input image
Dimension of the old image array:  1
Size of the old image array:  262144


In [6]:
print(img.shape)
print(img.size)
#print(img[1,1])

(262144,)
262144


In [7]:
# Conversion from 1D to 2D array
img.shape = (img.size // COLS,COLS)
print("New dimension of the array:", img.ndim)
print("----------------------------------------------------")
print(" The 2D array of the original image is: \n", img)
print("----------------------------------------------------")
print("The shape of the original image array is: ", img.shape)

New dimension of the array: 2
----------------------------------------------------
 The 2D array of the original image is: 
 [[220 229 230 ... 107 106  91]
 [206 228 229 ...  94  97  97]
 [212 227 226 ...  84  97 100]
 ...
 [ 75  62  72 ...  34  43  30]
 [ 34  50  60 ...  35  29  37]
 [ 49  47  62 ...  43  30  29]]
----------------------------------------------------
The shape of the original image array is:  (512, 512)


In [8]:
## Save the output image
#print("... Save the output image")
#img.astype('int8').tofile('NewImage.raw')
#print("... File successfully saved")
## Closing the file
#fin.close()

In [9]:
print(img.shape)

(512, 512)


In [10]:
a=getPixel(img,1,1)

NameError: name 'getPixel' is not defined