In [1]:
import numpy as np

In [2]:
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.figure as fig
rgb_weights = [0.2989, 0.5870, 0.1140]
imagex = matplotlib.image.imread("C:/Users/avish/Desktop/tomato12.jpg")

In [3]:
print("Data type", type(imagex))

Data type <class 'numpy.ndarray'>


In [4]:
grayscale_image = np.dot(imagex[...,:3], rgb_weights)

#dummy=np.dot(imagex[...,:3], rgb_weights)
#grayscale_image=(grayscale_image//1)

In [5]:
#k=0
#v=0
#for x in range (256):
#    for y in range (443):
#        grayscale_image[x,y]=k
#        k=0
#        for z in range (3):
#          #  v=result[k]
#            k=k+(imagex[x,y,z])
#          # print(imagex)

#print(imagex)
#print(imagex.shape)
#print(imagex.size)

In [6]:
#plt.imshow(grayscale_image, cmap=plt.get_cmap("gray"))
#plt.show()

In [7]:
#fig = plt.gcf()
#size = fig.get_size_inches()*fig.dpi
#print(size)
#print(fig.get_size_inches)
#print(fig.dpi) #resolution in dots per inch.
##print(grayscale_image.shape) #dimensions of the array
print(grayscale_image[175,290])
print(grayscale_image[150,300])
print(grayscale_image[210,310])

57.3132
88.05279999999999
51.798500000000004


In [8]:
print(imagex)

[[[251 255 254]
  [251 255 254]
  [251 255 254]
  ...
  [ 85 165 114]
  [ 85 165 114]
  [ 85 165 114]]

 [[251 255 254]
  [251 255 254]
  [251 255 254]
  ...
  [ 85 165 114]
  [ 86 164 114]
  [ 86 164 114]]

 [[251 255 254]
  [251 255 254]
  [253 255 254]
  ...
  [ 88 166 116]
  [ 88 166 116]
  [ 89 165 116]]

 ...

 [[ 95 159  10]
  [ 95 158   9]
  [ 96 156   8]
  ...
  [ 59  96   0]
  [ 59  96   0]
  [ 59  96   0]]

 [[ 95 159  11]
  [ 95 157  10]
  [ 96 156   9]
  ...
  [ 59  96   0]
  [ 59  96   0]
  [ 59  96   0]]

 [[ 94 158  10]
  [ 94 156   9]
  [ 95 155   8]
  ...
  [ 59  96   1]
  [ 59  96   1]
  [ 59  96   1]]]


In [9]:
#img= np.fromfile(grayscale_image, dtype = np.uint8, count = ROWS * COLS)  #Construct an array from data in a text or binary file

In [10]:
print(grayscale_image.shape)
print(imagex.shape)
print(type(grayscale_image))


(256, 443)
(256, 443, 3)
<class 'numpy.ndarray'>


In [11]:
##Save the output image
#print("... Save the output image")
#grayscale_image.astype('int8').tofile('as.jpg')
#print("... File successfully saved")
# Closing the file
#grayscale_image.close()
#grayscale_image[1,2]=5
#arr=grayscale_image

In [12]:
#print(grayscale_image)

In [13]:
print(grayscale_image.shape)

(256, 443)


In [14]:
#y = list(dummy)
#y[(0,0)] = "kiwi"
#dummy = tuple(y)

#print(dummy)

In [15]:
#lower_red = [0,150,50]---------->66
#upper_red = [10,255,255]-------->173

#     COL  COL  COL
#ROW
#ROW
#ROW

print(grayscale_image[1,90])
ROW=len(grayscale_image)
COL=len(grayscale_image[0])
print(ROW)
print(COL)

246.8357
256
443


In [16]:
#print(grayscale_image)
#arr=grayscale_image[0,0]
#print(arr)
tup1 = ("173","66")
print( tup1[0] )

for i in range (ROW):
    for j in range (COL):
        if(((grayscale_image[i,j])>56)and((grayscale_image[i,j])<57)):
            #grayscale_image[i,j]=((grayscale_image[i,j])/(grayscale_image[i,j]))*255
            grayscale_image[i,j]=(grayscale_image[i,j])*0
       # if((grayscale_image[i,j]==57.3132)or(grayscale_image[i,j]==88.05279999999999)or(grayscale_image[i,j]==51.798500000000004)):
        #    grayscale_image[i,j]=(grayscale_image[i,j])*0
        else:
           # grayscale_image[i,j]=(grayscale_image[i,j])*0
            grayscale_image[i,j]=((grayscale_image[i,j])/(grayscale_image[i,j]))*255
            
            
            
        

173


In [17]:
#import array as arr
 
# creating an array with integer type
# a[2,3]= arr.array('i', [1, 2, 3])

#for i in range (ROW):
 #   for j in range (COL):
  #      if (grayscale_image[i,j]<173)&(grayscale_image[i,j]>66):
   #          print(grayscale_image[i,j])
        #   redimg[i,j]=grayscale_image[i,j]
        #else:
           # redimg[i,j]=0

#for x in grayscale_image:  # outer loop  
 #   for i in x:  # inner loop  
  #      print(grayscale_image[i,x])
        #if (int(grayscale_image[i,x])<173)&(int(grayscale_image[i,x])>66):
   #         print(grayscale_image[i,x])
            #redimg[i,x]=grayscale_image[i,x]
        #else:
         #   redimg[i,x]=0


In [18]:
# creating an array with integer type
# a[2,3]= arr.array('i', [1, 2, 3])
#from array import *
#redimg=[[ROW],[COL]]

#for i in range (ROW):
 #   for j in range (COL):
  #      if (grayscale_image[i,j]<173)&(grayscale_image[i,j]>66):
   #         print(grayscale_image[i,j])
    #        redimg[i,j]=grayscale_image[i,j]
        

In [19]:
#x = ("apple", "banana", "cherry")
#y = list(grayscale_image)
#y[1] = "kiwi"
#grayscale_image = tuple(y)
#if type(grayscale_image) == list:
 #   print("a is a list")
#else:
 #   print("a is a tuple")

#print(grayscale_image)

In [20]:
#import array as arr
 
# creating an array with integer type
 #a= arr.array(1, [1, 2, 3])

In [21]:
# write a program to traverse every element of the two-dimensional array in Python.  
#Student_dt = [ [72, 85, 87, 90, 69], [80, 87, 65, 89, 85], [96, 91, 70, 78, 97], [90, 93, 91, 90, 94], [57, 89, 82, 69, 60] ]  
# Use for loop to print the entire elements of the two dimensional array.  
#for x in grayscale_image:  # outer loop  
 #   for i in x:  # inner loop  
        
       #print(i, end = " ") # print the elements  
    #print() 

In [22]:
#print(redimage)

In [23]:
import cv2
cv2.imwrite('C:/Users/avish/Desktop/aac.jpg',grayscale_image)

True

In [24]:
tup1 = ("173","68")
print( tup1[0] )


173


In [25]:
a=5
b=7

if ((6<b)and(6>a)):
    print(9)

9
