In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.figure as fig
import cv2
import math
#import

In [2]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.figure as fig
import cv2
import math

rgb_weights = [0.2989, 0.5870, 0.1140]
imagex = matplotlib.image.imread("C:/Users/avish/Desktop/New folder/tomato12.jpg")

print("Data type", type(imagex))

print(imagex[2,441])
print(imagex.size)
#imagex[0,0]=[,0,0]
#if imagex[0,0]
print(type(imagex))
print(imagex)

Data type <class 'numpy.ndarray'>
[ 88 166 116]
340224
<class 'numpy.ndarray'>
[[[251 255 254]
  [251 255 254]
  [251 255 254]
  ...
  [ 85 165 114]
  [ 85 165 114]
  [ 85 165 114]]

 [[251 255 254]
  [251 255 254]
  [251 255 254]
  ...
  [ 85 165 114]
  [ 86 164 114]
  [ 86 164 114]]

 [[251 255 254]
  [251 255 254]
  [253 255 254]
  ...
  [ 88 166 116]
  [ 88 166 116]
  [ 89 165 116]]

 ...

 [[ 95 159  10]
  [ 95 158   9]
  [ 96 156   8]
  ...
  [ 59  96   0]
  [ 59  96   0]
  [ 59  96   0]]

 [[ 95 159  11]
  [ 95 157  10]
  [ 96 156   9]
  ...
  [ 59  96   0]
  [ 59  96   0]
  [ 59  96   0]]

 [[ 94 158  10]
  [ 94 156   9]
  [ 95 155   8]
  ...
  [ 59  96   1]
  [ 59  96   1]
  [ 59  96   1]]]


In [3]:
rgb_weights = [0.2989, 0.5870, 0.1140]
imagex = matplotlib.image.imread("C:/Users/avish/Desktop/New folder/tomato12.jpg")

In [4]:
print("Data type", type(imagex))

Data type <class 'numpy.ndarray'>


In [5]:
#print(imagex)

In [6]:
#asd = tomato1.convert("RGB")
#Convert to RGB colorspace


#rgb_pixel_value = asd.getpixel((10,15))

In [7]:
pip install pillow


Note: you may need to restart the kernel to use updated packages.


In [8]:
#from PIL import Image

#img = Image.fromarray(array)
#img.save('testrgb.png')

In [9]:
import numpy as np

width = 5
height = 4

array = np.zeros([height, width, 3], dtype=np.uint8)

In [10]:
array[:,:] = [255, 128, 0]

In [11]:
from PIL import Image

img = Image.fromarray(array)
img.save('testrgb.png')

In [12]:
import numpy as np
from PIL import Image

array = np.zeros([100, 200, 3], dtype=np.uint8)
array[:,:50] = [255, 128, 0] #Orange left side
array[:,50:] = [0, 0, 255]   #Blue right side
array[50:,:] = [0, 0, 255] 
array[0,0]=[0,0,0]
img = Image.fromarray(array)
img.save('testrgb.png')
plt.show()

In [13]:
#for x in imagex:  # outer loop  
 #   for i in x:  # inner loop  
  #      print(imagex[i,x])

In [18]:
print(imagex[0,0])
print(imagex.size)
#imagex[0,0]=[,0,0]
#if imagex[0,0]
print(type(imagex))
print(imagex[0,0,0])
print(len(imagex[0]))
print(imagex.shape)

[251 255 254]
340224
<class 'numpy.ndarray'>
251
443
(256, 443, 3)


In [20]:
for x in ROW:  # outer loop  
    for i in COL:  # inner loop  
        print(imagex[x,i])

TypeError: 'int' object is not iterable

In [16]:
newarr = imagex.reshape(256,443*3)
#print(newarr)
print(newarr.shape)
ROW=len(newarr)
COL=len(newarr[0])
dum=imagex
redRange = np.zeros([256, 1329])
greenRange = np.zeros([256, 1329])
blueRange = np.zeros([256, 1329])
#type(imagex)
type(blueRange)

(256, 1329)


numpy.ndarray

In [17]:
for x in ROW:  # outer loop  
    for i in COL:  # inner loop  
        print(newarr[x,i])

TypeError: 'int' object is not iterable

In [ ]:
n=1
l=2
for i in range (ROW):
    for j in range (COL-3):
        j=j+3
        #print(newarr[i,j])
    
        x=newarr[i,j]
    
        if x>200:
            xx=1
        else:
            xx=0
        
        redRange[i,j]=xx
        
for m in range (ROW):
    for n in range (COL-3):
        n=n+3
        #print(newarr[m,n])
        
        y=newarr[m,n]
        if (y>30)and(y<200):
            yy=1
        else:
            yy=0
        greenRange[m,n]=yy
      #  redRange(newarr[m,l])
        
for b in range (ROW):
    for l in range (COL-3):
        l=l+3
        #print(newarr[b,l])
       # redRange(newarr[b,l])
    z=newarr[b,l]
    if (z>0)and(z<130):
        zz=1
    else:
        zz=0
    blueRange[b,l]=zz


In [ ]:
for v in range (ROW):
    for b in range (COL):
        print(redRange[v,b])
        
for i in range (ROW):
    for j in range (COL):
        
         redRange[i,j]
        

In [ ]:
print(imagex)


In [ ]:
cv2.imwrite('C:/Users/avish/Desktop/New folder/img.jpg',imagex)

In [ ]:
def redRange(x):
    if x>200:
        xx=1
    else:
        xx=0
    for xr in range (ROW):
        for yr in range (COL):
            redRange[xr,yr]==xx
    return xx

def greenRange(y):
    if (y>30)and(y<200):
        yy=1
    else:
        yy=0
    for xg in range (ROW):
        for yg in range (COL):
            redRange[xg,yg]==yy
    return yy

def blueRange(z):
    if (z>0)and(z<130):
        zz=1
    else:
        zz=0
    for bg in range (ROW):
        for bg in range (COL):
            redRange[zg,zg]==zz
    return zz


In [ ]:
if (0)and(1)and(1):
    print(1)