In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.figure as fig
import cv2
#import mathh

In [2]:
#rgb_weights = [0.2989, 0.5870, 0.1140]
imagex = matplotlib.image.imread("C:/Users/avish/Desktop/New folder/tomato12.jpg")

In [3]:
print(imagex.shape)
newarr = imagex.reshape(256,443*3)
print(newarr.shape)
ROW=len(newarr)
COL=len(newarr[0])
redRange = np.zeros([256, 1329])
greenRange = np.zeros([256, 1329])
blueRange = np.zeros([256, 1329])
print(newarr)

print(imagex.shape)
print(newarr[0,0])

#for x in range (ROW):
   # for y in range (COL):
      #  print(newarr[x,y])

(256, 443, 3)
(256, 1329)
[[251 255 254 ...  85 165 114]
 [251 255 254 ...  86 164 114]
 [251 255 254 ...  89 165 116]
 ...
 [ 95 159  10 ...  59  96   0]
 [ 95 159  11 ...  59  96   0]
 [ 94 158  10 ...  59  96   1]]
(256, 443, 3)
251


In [4]:
#for x in range (ROW):
   # for y in range (COL):
       # print(redRange[x,y])
print(redRange[0,0])  
print(redRange[0,0])

0.0
0.0


In [5]:
a = newarr[0]

In [6]:
for i in range (256):
    for j in range(0, COL, 3):
        x=newarr[i,j]
        
        z=newarr[i,j]
        if (z>0)and(z<130):
            yy=1
        else:
            yy=0
        blueRange[i,j]=yy


        
       # print(newarr[i,j])

for m in range (256):
    for n in range(1, COL, 3):
        
        y=newarr[m,n]
        if (y>30)and(y<200):
            yy=1
        else:
            yy=0
        greenRange[m,n]=yy
        
        
for a in range (256):
    for b in range(2, COL, 3):
        
        if x>200:
            xx=1
        else:
            xx=0
        redRange[a,b]=xx
        
#for x in range (ROW):
 #   for y in range (COL):
  #      print(blueRange[x,y])
    


In [ ]:
for x in range (256):
    for y in range (1329):
        if (redRange[x,y])and(greenRange[x,y])and(blueRange[x,y]):
            newarr[x,y]=0
        else:
            newarr[x,y]=255
                
                    

In [ ]:
#print(newarr)


In [ ]:
#print(newarr.shape)

In [ ]:
#for x in range (256):
    #for y in range (1329):
    #    print(newarr[x,y])

In [ ]:
#print(newarr)
result = newarr.flatten()

In [ ]:
#print(result)

In [ ]:
#B = np.reshape(340224,(256,443,3))

In [ ]:
k=0
v=0
for x in range (256):
    for y in range (443):
        for z in range (3):
            v=result[k]
            imagex[x,y,z]=v
            k=k+1
            print(imagex)

print(imagex)
print(imagex.shape)
print(imagex.size)

In [ ]:
cv2.imwrite('C:/Users/avish/Desktop/New folder/imge.jpg',imagex)